services:
  authentik-fh:
    pull_policy: missing
    labels:
      # Websecure
      traefik.http.routers.authentik-fh-insecure.rule: HostRegexp(`^.+\.${CATCHALL_DOMAIN}$`)
      traefik.http.routers.authentik-fh-insecure.priority: 1
      traefik.http.routers.authentik-fh.rule: HostRegexp(`^.+\.${CATCHALL_DOMAIN}$`)
      traefik.http.routers.authentik-fh.priority: 1
      traefik.http.routers.authentik-fh.middlewares: chain-Domain@file
      traefik.http.routers.authentik-fh.tls.certresolver: ''
      # WUD-FH
      wud.tag.include: '^\d+\.\d+\.\d+$$'
      wud.watch: true
      wud.link.template: https://github.com/goauthentik/authentik/releases/tag/$${major}.$${minor}.$${patch}

  authentik-fh-worker:
    pull_policy: missing
    labels:
      # WUD-FH
      wud.tag.include: '^\d+\.\d+\.\d+$$'
      wud.watch: true
      wud.link.template: https://github.com/goauthentik/authentik/releases/tag/$${major}.$${minor}.$${patch}

  authentik-fh-db:
    pull_policy: missing
    labels:
      # WUD-FH
      wud.tag.include: '^12-alpine$$'
      wud.watch: true
      wud.watch.digest: true

  authentik-fh-redis:
    pull_policy: missing
    labels:
      # WUD-FH
      wud.tag.include: '^alpine$$'
      wud.watch: true
      wud.watch.digest: true
