services:
  homeassistant-1:
    #image: ghcr.io/home-assistant/home-assistant:2025.3.0
    pull_policy: missing
    labels:
      # Websecure
      traefik.http.routers.homeassistant-1-migrated.middlewares: chain-Domain-auth@file
      traefik.http.routers.homeassistant-1-migrated.tls.certresolver: ''
      # WebSecure local IP
      traefik.http.routers.homeassistant-1-migrated-privip.rule: Host(`${APP_DOMAIN}`) && ClientIP(`${PRIVATE_IPV4}`)
      traefik.http.routers.homeassistant-1-migrated-privip.middlewares: chain-Domain@file
      traefik.http.routers.homeassistant-1-migrated-privip.entrypoints: websecure
      traefik.http.routers.homeassistant-1-migrated-privip.service: homeassistant-1-migrated
      traefik.http.routers.homeassistant-1-migrated-privip.priority: 100
      traefik.http.routers.homeassistant-1-migrated-privip.tls.certresolver: ''
      # WUD-FH
      wud.tag.include: '^\d+\.\d+\.\d+$$'
      wud.watch: true
      wud.link.template: https://github.com/home-assistant/core/releases/tag/$${major}.$${minor}.$${patch}
