services:
  vaultwarden:
    #image: vaultwarden/server:1.33.0
    pull_policy: missing
    environment:
      - SIGNUPS_ALLOWED=false # Change to false after first login
      - INVITATIONS_ALLOWED=false # Send invitation using admin page
      - DISABLE_ADMIN_TOKEN=false # true will disable the built in ADMIN_TOKEN used for authentication while also enabling the admin panel 
      - SHOW_PASSWORD_HINT=false
      - DOMAIN=${APP_PROTOCOL:-http}://${APP_DOMAIN}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=465
      - SMTP_SECURITY=force_tls
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_FROM=noreply.vaultwarden@${APP_DOMAIN}
      - SMTP_FROM_NAME=vaultwarden
      - LOG_FILE=/data/vaultwarden.log
      - LOG_LEVEL=warn # options are: "trace", "debug", "info", "warn", "error" or "off".
      - EXTENDED_LOGGING=false
    labels:
      # Websecure
      traefik.http.routers.vaultwarden-migrated.middlewares: chain-Domain-auth@file
      traefik.http.routers.vaultwarden-migrated.tls.certresolver: ''
      # WebSecure local IP
      traefik.http.routers.vaultwarden-migrated-privip.rule: Host(`${APP_DOMAIN}`) && ClientIP(`${PRIVATE_IPV4}`)
      traefik.http.routers.vaultwarden-migrated-privip.middlewares: chain-Domain@file
      traefik.http.routers.vaultwarden-migrated-privip.entrypoints: websecure
      traefik.http.routers.vaultwarden-migrated-privip.service: vaultwarden-migrated
      traefik.http.routers.vaultwarden-migrated-privip.priority: 100
      traefik.http.routers.vaultwarden-migrated-privip.tls.certresolver: ''
      # WUD-FH
      wud.tag.include: '^\d+\.\d+\.\d+$$'
      wud.watch: true
      wud.link.template: https://github.com/dani-garcia/vaultwarden/releases/tag/$${major}.$${minor}.$${patch}
