services:
  wallos:
    labels:
      # Websecure
      traefik.http.routers.wallos.middlewares: chain-Domain-auth@file
      traefik.http.routers.wallos.tls.certresolver: ''
      # WebSecure local IP
      traefik.http.routers.wallos-privip.rule: Host(`${APP_DOMAIN}`) && ClientIP(`${PRIVATE_IPV4}`)
      traefik.http.routers.wallos-privip.middlewares: chain-Domain@file
      traefik.http.routers.wallos-privip.entrypoints: websecure
      traefik.http.routers.wallos-privip.service: wallos
      traefik.http.routers.wallos-privip.priority: 100
      traefik.http.routers.wallos-privip.tls.certresolver: ''
