version: '3'

services:
  wallos:
    labels:
      # Websecure
      traefik.http.routers.wallos.middlewares: geoblock@file
      # Local domain secure
      traefik.http.routers.wallos-local.middlewares: local-ipallowlist@file
