services:
  runtipi-reverse-proxy:
    #image: traefik:v3.2.3
    env_file: ./user-config/tipi-compose.env
    ports:
      - 8080:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./user-config/traefik/etc:/etc/traefik
      - ./app-data/traefik/plugins-local:/plugins-local
      - ./app-data/traefik/shared:/shared

  runtipi:
    labels:
      # ---- General ----- #

      # ---- Dashboard ----- #
      # Local ip
      traefik.http.routers.dashboard.rule: (Host(`${INTERNAL_IP}`) || Host(`tipi.${LOCAL_DOMAIN}`)) && PathPrefix(`/`)
      # Websecure
      traefik.http.routers.dashboard-secure.middlewares: chain-Domain-auth@file
      traefik.http.routers.dashboard-secure.tls.domains[0].main: ${WILDCARD_DOMAIN}
      traefik.http.routers.dashboard-secure.tls.domains[0].sans: "*.${WILDCARD_DOMAIN}"
      # Secure
      traefik.http.routers.dashboard-local.middlewares: ipAllowList-local@file

      # ---- Socket ----- #
      # Local ip
      traefik.http.routers.socket.rule: (Host(`${INTERNAL_IP}`) || Host(`tipi.${LOCAL_DOMAIN}`)) && PathPrefix(`/api/socket.io`)
      # Websecure
      traefik.http.routers.socket-insecure.rule: Host(`${DOMAIN}`) && PathPrefix(`/api/socket.io`)
      traefik.http.routers.socket-secure.rule: Host(`${DOMAIN}`) && PathPrefix(`/api/socket.io`)
      traefik.http.routers.socket-secure.middlewares: chain-Domain-auth@file
      traefik.http.routers.socket-secure.tls.certresolver: ''
      # Local domain
      traefik.http.routers.socket-local-insecure.rule: (Host(`${INTERNAL_IP}`) || Host(`tipi.${LOCAL_DOMAIN}`)) && PathPrefix(`/api/socket.io`)
      # Secure
      traefik.http.routers.socket-local.rule: (Host(`${INTERNAL_IP}`) || Host(`tipi.${LOCAL_DOMAIN}`)) && PathPrefix(`/api/socket.io`)
      traefik.http.routers.socket-local.middlewares: chain-localDomain@file
