version: '3.7'

services:
  tipi-worker:
    labels:
      # Local ip
      traefik.http.routers.worker.rule: (Host(`${INTERNAL_IP}`) || Host(`tipi.${LOCAL_DOMAIN}`)) && PathPrefix(`/worker`)
      # Websecure
      traefik.http.routers.worker-secure.middlewares: geoblock@file

  tipi-dashboard:
    labels:
      # Local ip
      traefik.http.routers.dashboard.rule: (Host(`${INTERNAL_IP}`) || Host(`tipi.${LOCAL_DOMAIN}`)) && PathPrefix(`/`)
      # Websecure
      traefik.http.routers.dashboard-secure.middlewares: authentik@file, geoblock@file

  tipi-reverse-proxy:
    ports:
      - 8080:8080
    volumes:
      - ./app-data/traefik:/etc/traefik
      - ./app-data/traefik/shared:/shared
      - /var/log/traefik/:/var/log/