services:
  wud-fh:
    environment:
      - WUD_REGISTRY_HUB_PUBLIC_LOGIN=${WUD_REGISTRY_HUB_PUBLIC_LOGIN}
      - WUD_REGISTRY_HUB_PUBLIC_PASSWORD=${WUD_REGISTRY_HUB_PUBLIC_PASSWORD}
      - WUD_REGISTRY_LSCR_PRIVATE_USERNAME=${WUD_REGISTRY_LSCR_PRIVATE_USERNAME}
      - WUD_REGISTRY_LSCR_PRIVATE_TOKEN=${WUD_REGISTRY_LSCR_PRIVATE_TOKEN}
    labels:
      # Websecure
      traefik.http.routers.wud-fh.middlewares: chain-Domain-auth@file
      traefik.http.routers.wud-fh.tls.certresolver: ''
      # WebSecure local IP
      traefik.http.routers.wud-fh-privip.rule: Host(`${APP_DOMAIN}`) && ClientIP(`${PRIVATE_IPV4}`)
      traefik.http.routers.wud-fh-privip.middlewares: chain-Domain@file
      traefik.http.routers.wud-fh-privip.entrypoints: websecure
      traefik.http.routers.wud-fh-privip.service: wud-fh
      traefik.http.routers.wud-fh-privip.priority: 100
      traefik.http.routers.wud-fh-privip.tls.certresolver: ''
      # WUD
      wud.tag.include: '^\d+\.\d+\.\d+$$'
