version: "3.7"
services:
  2fauth:
    environment:
      - ASSET_URL=https://2fauth.${LOCAL_DOMAIN}
      - APP_URL=https://2fauth.${LOCAL_DOMAIN}
      - APP_TIMEZONE=${TZ}
    labels:
      # Local domain secure
      traefik.http.routers.2fauth-local.middlewares: local-ipallowlist@file
