services:
  2fauth:
    environment:
      # Timezone: Runtipi
      - APP_TIMEZONE=${TZ}
      # URLs: [Loc]
      - ASSET_URL=https://2fauth.${LOCAL_DOMAIN}
      - APP_URL=https://2fauth.${LOCAL_DOMAIN}
      # OAuth2: [Loc]
      - OPENID_AUTHORIZE_URL=${OPENID_AUTHORIZE_URL}
      - OPENID_TOKEN_URL=${OPENID_TOKEN_URL}
      - OPENID_USERINFO_URL=${OPENID_USERINFO_URL}
      - OPENID_CLIENT_ID=${OPENID_CLIENT_ID}
      - OPENID_CLIENT_SECRET=${OPENID_CLIENT_SECRET}
    labels:
      # LocalIPs: [Loc], ForwardAuth: [Loc]
      traefik.http.routers.2fauth-local.middlewares: chain-localDomain-auth@file
