version: '3'

services:
  pinchflat:
    volumes:
      - ${APP_USER_DATA_DIR}/video/youtube/:/downloads
    labels:
      # Websecure
      traefik.http.routers.pinchflat.middlewares: authentik@file, geoblock@file
      # Local domain secure
      traefik.http.routers.pinchflat-local.middlewares: local-ipallowlist@file
