version: '3'
services:
  pinchflat:
    ports: !reset []
    volumes:
      - ${APP_USER_DATA_DIR}/video/youtube/:/downloads
    labels:
      # Websecure
      traefik.http.routers.pinchflat.middlewares: plugin-geoblock@file, forwardAuth-authentik@file
      traefik.http.routers.pinchflat.tls.certresolver: ''
      # Local domain secure
      traefik.http.routers.pinchflat-local.middlewares: ipAllowList-none@file
