services:
  pinchflat:
    volumes:
      - ${APP_USER_DATA_DIR}/video/youtube/:/downloads
    labels:
      # Websecure
      traefik.http.routers.pinchflat.middlewares: chain-Domain-auth@file
      traefik.http.routers.pinchflat.tls.certresolver: ''
