services:
  joplin:
    # Ensure the image is not pulled if present
    pull_policy: missing
    labels:
      # Websecure
      # Use the chain-Domain middleware for domain handling
      traefik.http.routers.joplin-falkheiland.middlewares: chain-Domain@file
      # Use the default certresolver
      traefik.http.routers.joplin-falkheiland.tls.certresolver: ''

  joplin-db:
    # Ensure the image is not pulled if present
    pull_policy: missing
    networks:
      # This network is shared with the docker-db-backup app
      shared_docker-db-backup_network:
        gw_priority: 0

networks:
  # This network is shared with the docker-db-backup app
  shared_docker-db-backup_network:
    external: true
