services:
  metube:
    image: ghcr.io/alexta69/metube:2025-04-16
    pull_policy: missing
    volumes:
      - ${ROOT_FOLDER_HOST}/media/data/video/youtube/:/downloads
    environment:
      - DOWNLOAD_DIRS_INDEXABLE=true
      - DELETE_FILE_ON_TRASHCAN=true
    labels:
      # Websecure
      traefik.http.routers.metube-migrated.middlewares: chain-Domain-auth@file
      traefik.http.routers.metube-migrated.tls.certresolver: ''
      # WUD-FH
      wud.tag.include: '^\d+-\d+-\d+$$'
      wud.watch: true
      wud.link.template: https://github.com/alexta69/metube/pkgs/container/metube
