services:
  linkwarden:
    pull_policy: missing
    environment:
      # https://docs.linkwarden.app/self-hosting/environment-variables
      #- PAGINATION_TAKE_COUNT=
      #- STORAGE_FOLDER=
      #- AUTOSCROLL_TIMEOUT=
      #- NEXT_PUBLIC_CREDENTIALS_ENABLED=
      #- DISABLE_NEW_SSO_USERS=
      #- RE_ARCHIVE_LIMIT=
      #- NEXT_PUBLIC_MAX_FILE_SIZE=
      #- MAX_LINKS_PER_USER=
      #- ARCHIVE_TAKE_COUNT=
      #- BROWSER_TIMEOUT=
      # https://github.com/linkwarden/linkwarden/issues/381#issuecomment-1872982427
      - IGNORE_UNAUTHORIZED_CA=true
      # https://docs.linkwarden.app/self-hosting/sso-oauth#authentik
      - NEXT_PUBLIC_AUTHENTIK_ENABLED=true
      - AUTHENTIK_ISSUER=${AUTHENTIK_ISSUER}
      - AUTHENTIK_CLIENT_ID=${AUTHENTIK_CLIENT_ID}
      - AUTHENTIK_CLIENT_SECRET=${AUTHENTIK_CLIENT_SECRET}
    labels:
      # Websecure
      traefik.http.routers.linkwarden-migrated.middlewares: chain-Domain-auth@file
      traefik.http.routers.linkwarden-migrated.tls.certresolver: ''
      # WebSecure local IP
      traefik.http.routers.linkwarden-migrated-privip.rule: Host(`${APP_DOMAIN}`) && ClientIP(`${PRIVATE_IPV4}`)
      traefik.http.routers.linkwarden-migrated-privip.middlewares: chain-Domain@file
      traefik.http.routers.linkwarden-migrated-privip.entrypoints: websecure
      traefik.http.routers.linkwarden-migrated-privip.service: linkwarden-migrated
      traefik.http.routers.linkwarden-migrated-privip.priority: 100
      traefik.http.routers.linkwarden-migrated-privip.tls.certresolver: ''
      # WUD-FH
      wud.tag.include: '^\d+\.\d+\.\d+$$'
      wud.watch: true
      wud.link.template: https://github.com/linkwarden/linkwarden/releases/tag/v$${major}.$${minor}.$${patch}

  linkwarden-db:
    pull_policy: missing
    image: postgres:16-alpine
    networks:
      shared_docker-db-backup_network:
        gw_priority: 0
    labels:
      # WUD-FH
      wud.tag.include: '^16-alpine$$'
      wud.watch.digest: true
      wud.watch: true
      wud.link.template: https://github.com/postgres/postgres/tag/REL_$${major}_$${minor}

networks:
  shared_docker-db-backup_network:
    external: true
