services:
  cup:
    pull_policy: missing
    labels:
      # Websecure
      traefik.http.routers.cup-falkheiland.middlewares: chain-Domain-auth@file
      traefik.http.routers.cup-falkheiland.tls.certresolver: ''
