services:
  bookstack:
    labels:
      # Websecure
      traefik.http.routers.bookstack.middlewares: authentik@file, geoblock@file

  dbbackup:
    image: tiredofit/db-backup:4.1.9
    container_name: bookstack-db-backup
    environment:
      - DEFAULT_COMPRESSION=GZ
      - DB01_TYPE=mysql
      - DB01_HOST=bookstack-db
      - DB01_NAME=bookstackapp
      - DB01_USER=tipi
      - DB01_PASS=${BOOKSTACK_DB_PASS}
      - CONTAINER_ENABLE_MONITORING=FALSE
      - DEFAULT_CLEANUP_TIME=1440
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA_DIR}/data/db-backup:/backup
    depends_on:
      - bookstack-db
