services:
  searxng:
    #image: searxng/searxng:2025.3.11-3fe602a46
    pull_policy: missing
    labels:
      # Websecure
      traefik.http.routers.searxng-migrated.middlewares: chain-Domain-auth@file
      traefik.http.routers.searxng-migrated.tls.certresolver: ''
      # WebSecure local IP
      traefik.http.routers.searxng-migrated-privip.rule: Host(`${APP_DOMAIN}`) && ClientIP(`${PRIVATE_IPV4}`)
      traefik.http.routers.searxng-migrated-privip.middlewares: chain-Domain@file
      traefik.http.routers.searxng-migrated-privip.entrypoints: websecure
      traefik.http.routers.searxng-migrated-privip.service: searxng-migrated
      traefik.http.routers.searxng-migrated-privip.priority: 100
      traefik.http.routers.searxng-migrated-privip.tls.certresolver: ''
      # WUD-FH
      wud.tag.include: '^latest+$$'
      wud.watch: true
      wud.watch.digest: true
