version: '3.7'

services:
  ntfy:
    labels:
      # Websecure
      traefik.http.routers.ntfy.middlewares: default-auth@file

      # Local domain secure
      traefik.http.routers.ntfy-local.middlewares: default-auth@file
