services:
  navidrome:
    environment:
      ND_BASEURL: "https://navidrome.${LOCAL_DOMAIN}"
      ND_REVERSEPROXYUSERHEADER: "X-authentik-username" #"Remote-User"
      ND_REVERSEPROXYWHITELIST: "0.0.0.0/0"
    labels:
      # Websecure
      traefik.http.routers.navidrome.middlewares: chain-Domain-auth@file
      traefik.http.routers.navidrome.tls.certresolver: ''
      # WebSecure local IP
      traefik.http.routers.navidrome-privip.rule: Host(`${APP_DOMAIN}`) && ClientIP(`${PRIVATE_IPV4}`)
      traefik.http.routers.navidrome-privip.middlewares: chain-Domain@file
      traefik.http.routers.navidrome-privip.entrypoints: websecure
      traefik.http.routers.navidrome-privip.service: navidrome
      traefik.http.routers.navidrome-privip.priority: 100
      traefik.http.routers.navidrome-privip.tls.certresolver: ''
      # WUD
      wud.tag.include: '^\d+\.\d+\.\d+$$'
