version: "3"
services:
  navidrome:
    environment:
      ND_BASEURL: "https://navidrome.${LOCAL_DOMAIN}"
      ND_REVERSEPROXYUSERHEADER: "X-authentik-username" #"Remote-User"
      ND_REVERSEPROXYWHITELIST: "0.0.0.0/0"
    volumes:
      - ${APP_USER_DATA_DIR}/music:/music:ro
    labels:
      # # Websecure
      # traefik.http.routers.navidrome.middlewares: plugin-geoblock@file
      # Local domain secure
      traefik.http.routers.navidrome-local.middlewares: ipAllowList-local@file, forwardAuth-authentik@file
