services:
  navidrome:
    environment:
      ND_BASEURL: "https://navidrome.${LOCAL_DOMAIN}"
      ND_REVERSEPROXYUSERHEADER: "X-authentik-username" #"Remote-User"
      ND_REVERSEPROXYWHITELIST: "0.0.0.0/0"
    volumes:
      - ${APP_USER_DATA_DIR}/music:/music:ro
    labels:
      # Local domain secure
      traefik.http.routers.navidrome-local.middlewares: chain-localDomain-auth@file
