services:
  paperless-ngx-webserver:
    pull_policy: missing
    volumes:
      - ${APP_USER_DATA_DIR}/tipi/paperlessngx/media:/usr/src/paperless/media
      - ${APP_USER_DATA_DIR}/tipi/paperlessngx/export:/usr/src/paperless/export
      - ${APP_USER_DATA_DIR}/scan:/usr/src/paperless/consume
    environment:
      PAPERLESS_CONSUMER_POLLING: 300
      PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect
      PAPERLESS_SOCIALACCOUNT_PROVIDERS: >
        {
          "openid_connect": {
            "APPS": [
              {
                "provider_id": "authentik",
                "name": "Authentik",
                "client_id": "${OAUTH2_CLIENT_ID}",
                "secret": "${OAUTH2_SECRET}",
                "settings": {
                  "server_url": "${OAUTH2_SERVER_URL}/application/o/paperless-ngx/.well-known/openid-configuration"
                }
              }
            ],
            "OAUTH_PKCE_ENABLED": "True"
          }
        }
      PAPERLESS_REDIRECT_LOGIN_TO_SSO: true
      PAPERLESS_DISABLE_REGULAR_LOGIN: true
    labels:
      # Websecure
      traefik.http.routers.paperless-ngx-falkheiland.middlewares: chain-Domain-auth@file
      traefik.http.routers.paperless-ngx-falkheiland.tls.certresolver: ''
      # WebSecure local IP
      traefik.http.routers.paperless-ngx-falkheiland-privip.rule: Host(`${APP_DOMAIN}`) && ClientIP(`${PRIVATE_IPV4}`)
      traefik.http.routers.paperless-ngx-falkheiland-privip.middlewares: chain-Domain@file
      traefik.http.routers.paperless-ngx-falkheiland-privip.entrypoints: websecure
      traefik.http.routers.paperless-ngx-falkheiland-privip.service: paperless-ngx-falkheiland
      traefik.http.routers.paperless-ngx-falkheiland-privip.priority: 100
      traefik.http.routers.paperless-ngx-falkheiland-privip.tls.certresolver: ''

  paperless-ngx-broker:
    pull_policy: missing

  paperless-ngx-db:
    pull_policy: missing
    networks:
      shared_docker-db-backup_network:
        gw_priority: 0

  paperless-ngx-gotenberg:
    pull_policy: missing

  paperless-ngx-tika:
    pull_policy: missing

networks:
  shared_docker-db-backup_network:
    external: true
