version: "3.7"

services:
  authentik-db:
    networks:
      - backend_network

  dbbackup:
    image: tiredofit/db-backup:4.0.34
    container_name: authentik-db-backup
    environment:
      - DEFAULT_COMPRESSION=GZ
      - DB01_TYPE=pgsql
      - DB01_HOST=authentik-db
      - DB01_NAME=authentik
      - DB01_USER=authentik
      - DB01_PASS=${AUTHENTIK_DB_PASSWORD}
      - CONTAINER_ENABLE_MONITORING=FALSE
      - DEFAULT_CLEANUP_TIME=1440
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA_DIR}/data/db-backup:/backup
    depends_on:
      - authentik-db
    networks:
      - backend_network

networks:
  backend_network:
