version: "3.7"

services:
  authentik:
    labels:
      # Websecure
      traefik.http.routers.authentik.middlewares: plugin-geoblock@file
      # Local domain secure
      traefik.http.routers.authentik-local.middlewares: ipAllowList-local@file

  dbbackup:
    image: tiredofit/db-backup:4.1.9
    container_name: authentik-db-backup
    environment:
      - DEFAULT_COMPRESSION=GZ
      - DB01_TYPE=pgsql
      - DB01_HOST=authentik-db
      - DB01_NAME=authentik
      - DB01_USER=authentik
      - DB01_PASS=${AUTHENTIK_DB_PASSWORD}
      - CONTAINER_ENABLE_MONITORING=FALSE
      - DEFAULT_CLEANUP_TIME=1440
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA_DIR}/data/db-backup:/backup
    depends_on:
      - authentik-db
    networks:
      - tipi_main_network
