services:
  authentik:
    labels:
      # Websecure
      traefik.http.routers.authentik-insecure.rule: HostRegexp(`^.+\.${CATCHALL_DOMAIN}$`)
      traefik.http.routers.authentik-insecure.priority: 1
      traefik.http.routers.authentik.rule: HostRegexp(`^.+\.${CATCHALL_DOMAIN}$`)
      traefik.http.routers.authentik.priority: 1
      traefik.http.routers.authentik.middlewares: chain-Domain@file
      traefik.http.routers.authentik.tls.certresolver: ''

  dbbackup:
    image: tiredofit/db-backup:4.1.9
    container_name: authentik-db-backup
    environment:
      - DEFAULT_COMPRESSION=GZ
      - DB01_TYPE=pgsql
      - DB01_HOST=authentik-db
      - DB01_NAME=authentik
      - DB01_USER=authentik
      - DB01_PASS=${AUTHENTIK_DB_PASSWORD}
      - CONTAINER_ENABLE_MONITORING=FALSE
      - DEFAULT_CLEANUP_TIME=1440
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA_DIR}/data/db-backup:/backup
    depends_on:
      - authentik-db
    networks:
      - tipi_main_network
