http:
  serversTransports:
    insecuretransport:
      insecureSkipVerify: true
  middlewares:
    redirectScheme-default:
      redirectScheme:
        scheme: https
        permanent: true
    # Note: when used in docker-compose.yml all dollar signs in the hash need to be doubled for escaping.
    # To create a user:password pair, the following command can be used:
    # echo $(htpasswd -nb user password) | sed -e s/\\$/\\$\\$/g
    #
    # Also note that dollar signs should NOT be doubled when they not evaluated (e.g. Ansible docker_container module).
    # When used in .env file with go templating, dollar signs HAVE TO be doubled
    basicAuth-default:
      basicAuth:
        users:
          - '{{env "BASICAUTH_DEFAULT_USER01"}}'
    forwardauth-crowdsec-bouncer:
      forwardauth:
        address: http://crowdsec-bouncer-traefik:8080/api/v1/forwardAuth
        trustForwardHeader: true
    forwardAuth-authentik:
      forwardAuth:
        address: http://authentik:9000/outpost.goauthentik.io/auth/traefik
        trustForwardHeader: true
        authResponseHeaders:
          - X-authentik-username
          - X-authentik-groups
          - X-authentik-email
          - X-authentik-name
          - X-authentik-uid
          - X-authentik-jwt
          - X-authentik-meta-jwks
          - X-authentik-meta-outpost
          - X-authentik-meta-provider
          - X-authentik-meta-app
          - X-authentik-meta-version
    plugin-geoblock:
      plugin:
        traefik-plugin-geoblock:
          # Enable this plugin?
          enabled: true
          # Path to ip2location database file
          databaseFilePath: /plugins-local/src/github.com/nscuro/traefik-plugin-geoblock/IP2LOCATION-LITE-DB1.IPV6.BIN
          # Whitelist of countries to allow (ISO 3166-1 alpha-2)
          # allowedCountries: [ "DE" ]
          allowedCountries: [ '{{env "PLUGIN_GEOBLOCK_ALLOWEDCOUNTRIES"}}' ]
          # Blocklist of countries to block (ISO 3166-1 alpha-2)
          # blockedCountries: [ "RU" ]
          # Default allow indicates that if an IP is in neither block list nor allow lists, it should be allowed.
          defaultAllow: false
          # Allow requests from private / internal networks?
          allowPrivate: true
          # HTTP status code to return for disallowed requests (default: 403)
          disallowedStatusCode: 204
          # Add CIDR to be whitelisted, even if in a non-allowed country
          # allowedIPBlocks: ["66.249.64.0/19"]
          # Add CIDR to be blacklisted, even if in an allowed country or IP block
          # blockedIPBlocks: ["66.249.64.5/32"]
    ipAllowList-local:
      ipAllowList:
        sourceRange:
          - '{{env "IPALLOWLIST_LOCAL_SOURCERANGE01"}}'
    ipAllowList-none:
      ipAllowList:
        sourceRange:
          - '{{env "IPALLOWLIST_NONE_SOURCERANGE01"}}'
        ipStrategy:
          excludedIPs:
            - '{{env "IPALLOWLIST_NONE_EXCLUDEDIPS"}}'

  routers:
    service01:
      entryPoints:
        - "web"
      rule: 'Host(`{{env "SERVICE01_FQDN"}}`)'
      middlewares:
        - redirectScheme-default@file
      service: service01
    service01secure:
      entryPoints:
        - "websecure"
      rule: 'Host(`{{env "SERVICE01_FQDN"}}`)'
      middlewares:
        - plugin-geoblock@file
        - forwardAuth-authentik@file
      tls:
        options: sniStrictFalse@file
      service: service01

  services:
    service01:
      loadBalancer:
        serversTransport: insecuretransport
        servers:
          - url: '{{env "SERVICE01_URL"}}'
        passHostHeader: true

tls:
  options:
    default:
      minVersion: VersionTLS13
      cipherSuites:
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256
      curvePreferences:
        - CurveP521
        - CurveP384
      sniStrict: true
    sniStrictFalse:
      minVersion: VersionTLS13
      cipherSuites:
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256
      curvePreferences:
        - CurveP521
        - CurveP384
      sniStrict: false
  certificates:
    - certFile: /etc/traefik/tls/cert.pem
      keyFile: /etc/traefik/tls/key.pem
