version: "3.7"

services:

  immich:
    volumes:
      - /nfs/tipi/immich:/usr/src/app/upload

  immich-microservices:
    volumes:
      - /nfs/tipi/immich:/usr/src/app/upload

  immich-machine-learning:
    volumes:
      - /nfs/tipi/immich:/usr/src/app/upload
