version: "3.7"

services:

  immich:
    volumes:
      - ${APP_USER_DATA_DIR}/immich:/usr/src/app/upload

  immich-microservices:
    volumes:
      - ${APP_USER_DATA_DIR}/immich:/usr/src/app/upload

  immich-machine-learning:
    volumes:
      - ${APP_USER_DATA_DIR}/immich:/usr/src/app/upload
