version: '3.7'
services:
  paperless-ngx:
    volumes:
      - ${APP_USER_DATA_DIR}/tipi/paperlessngx/media:/usr/src/paperless/media
      - ${APP_USER_DATA_DIR}/tipi/paperlessngx/export:/usr/src/paperless/export
      - ${APP_USER_DATA_DIR}/scan:/usr/src/paperless/consume
    environment:
      PAPERLESS_TIME_ZONE: Europe/Berlin
      PAPERLESS_OCR_LANGUAGE: deu+eng
      PAPERLESS_CONSUMER_POLLING: 300
      PAPERLESS_ENABLE_HTTP_REMOTE_USER: TRUE
      PAPERLESS_HTTP_REMOTE_USER_HEADER_NAME: HTTP_X_AUTHENTIK_USERNAME
    labels:
      # Websecure
      traefik.http.routers.paperless-ngx.middlewares: authentik@file, geoblock@file

  db:
    image: docker.io/library/postgres:15
    networks:
      - backend_network

  dbbackup:
    image: tiredofit/db-backup:4.0.34
    container_name: paperless-ngx-db-backup
    environment:
      - DEFAULT_COMPRESSION=GZ
      - DB01_TYPE=pgsql
      - DB01_HOST=db
      - DB01_NAME=paperless
      - DB01_USER=paperless
      - DB01_PASS=paperless
      - CONTAINER_ENABLE_MONITORING=FALSE
      - DEFAULT_CLEANUP_TIME=1440
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA_DIR}/data/db-backup:/backup
    depends_on:
      - db
    networks:
      - backend_network

networks:
  backend_network:
