services:
  navidrome:
    pull_policy: missing
    environment:
      ND_BASEURL: "https://navidrome.${LOCAL_DOMAIN}"
      ND_REVERSEPROXYUSERHEADER: "X-authentik-username" #"Remote-User"
      ND_REVERSEPROXYWHITELIST: "0.0.0.0/0"
    labels:
      # Websecure
      traefik.http.routers.navidrome-migrated.middlewares: chain-Domain-auth@file
      traefik.http.routers.navidrome-migrated.tls.certresolver: ''
      # WebSecure local IP
      traefik.http.routers.navidrome-migrated-privip.rule: Host(`${APP_DOMAIN}`) && ClientIP(`${PRIVATE_IPV4}`)
      traefik.http.routers.navidrome-migrated-privip.middlewares: chain-Domain@file
      traefik.http.routers.navidrome-migrated-privip.entrypoints: websecure
      traefik.http.routers.navidrome-migrated-privip.service: navidrome-migrated
      traefik.http.routers.navidrome-migrated-privip.priority: 100
      traefik.http.routers.navidrome-migrated-privip.tls.certresolver: ''
      # WUD-FH
      wud.tag.include: '^\d+\.\d+\.\d+$$'
      wud.watch: true
      wud.link.template: https://github.com/navidrome/navidrome/releases/tag/v$${major}.$${minor}.$${patch}
