services:
  homeassistant:
    # Ensure the image is not pulled if present
    pull_policy: missing
    labels:
      # Websecure
      # Use the chain-Domain-auth middleware for domain handling
      traefik.http.routers.homeassistant-falkheiland.middlewares: chain-Domain-auth@file
      # Use the default certresolver
      traefik.http.routers.homeassistant-falkheiland.tls.certresolver: ''
      # WebSecure local IP
      # Use additional router for local access
      traefik.http.routers.homeassistant-falkheiland-privip.rule: Host(`${APP_DOMAIN}`) && ClientIP(`${PRIVATE_IPV4}`)
      traefik.http.routers.homeassistant-falkheiland-privip.middlewares: chain-Domain@file
      traefik.http.routers.homeassistant-falkheiland-privip.entrypoints: websecure
      traefik.http.routers.homeassistant-falkheiland-privip.service: homeassistant-falkheiland
      traefik.http.routers.homeassistant-falkheiland-privip.priority: 100
      traefik.http.routers.homeassistant-falkheiland-privip.tls.certresolver: ''
