services:
  pinchflat:
    pull_policy: missing
    volumes:
      - ${ROOT_FOLDER_HOST}/media/data/video/youtube/:/downloads
    labels:
      # Websecure
      traefik.http.routers.pinchflat-migrated.middlewares: chain-Domain-auth@file
      traefik.http.routers.pinchflat-migrated.tls.certresolver: ''
      # WUD-FH
      wud.watch: true
      wud.tag.include: '^v\d+\.\d+\.\d+$$'
      wud.link.template: https://github.com/kieraneglin/pinchflat/releases/tag/v$${major}.$${minor}.$${patch}
