services:
  jellyfin:
    pull_policy: missing
    labels:
      # Websecure
      traefik.http.routers.jellyfin-migrated.middlewares: chain-Domain-auth@file
      traefik.http.routers.jellyfin-migrated.tls.certresolver: ''
      # WebSecure local IP
      traefik.http.routers.jellyfin-migrated-privip.rule: Host(`${APP_DOMAIN}`) && ClientIP(`${PRIVATE_IPV4}`)
      traefik.http.routers.jellyfin-migrated-privip.middlewares: chain-Domain@file
      traefik.http.routers.jellyfin-migrated-privip.entrypoints: websecure
      traefik.http.routers.jellyfin-migrated-privip.service: jellyfin-migrated
      traefik.http.routers.jellyfin-migrated-privip.priority: 100
      traefik.http.routers.jellyfin-migrated-privip.tls.certresolver: ''
      # WUD-FH
      wud.tag.include: '^\d{2,2}\.\d+\.\d+$$'
      wud.watch: true
      wud.link.template: https://github.com/jellyfin/jellyfin/releases/tag/v$${major}.$${minor}.$${patch}
