version: '3'

services:
  homeassistant-1:
    labels:
      # Websecure
      traefik.http.routers.homeassistant.middlewares: authentik@file, geoblock@file
      # Local domain secure
      traefik.http.routers.homeassistant-local.middlewares: local-ipallowlist@file
