api:
  dashboard: true
  insecure: true
  debug: false

providers:
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    watch: true
    exposedByDefault: false
  file:
    directory: /etc/traefik/dynamic
    watch: true

entryPoints:
  web:
    address: ':80'

  websecure:
    address: ':443'
    http:
      tls:
        certResolver: myresolver
      middlewares:
        - forwardauth-crowdsec-bouncer@file

certificatesResolvers:
  myresolver:
    acme:
      storage: /shared/acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 3
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
log:
  level: ERROR

metrics:
  prometheus:
    manualRouting: true
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true

experimental:
  plugins:
    traefik-plugin-geoblock:
      moduleName: "github.com/nscuro/traefik-plugin-geoblock"
      version: "v0.14.0"
