services:
  linkwarden:
    pull_policy: missing
    environment:
      # https://docs.linkwarden.app/self-hosting/environment-variables
      #- PAGINATION_TAKE_COUNT=
      #- STORAGE_FOLDER=
      #- AUTOSCROLL_TIMEOUT=
      #- NEXT_PUBLIC_CREDENTIALS_ENABLED=
      #- DISABLE_NEW_SSO_USERS=
      #- RE_ARCHIVE_LIMIT=
      #- NEXT_PUBLIC_MAX_FILE_SIZE=
      #- MAX_LINKS_PER_USER=
      #- ARCHIVE_TAKE_COUNT=
      #- BROWSER_TIMEOUT=
      # https://github.com/linkwarden/linkwarden/issues/381#issuecomment-1872982427
      - IGNORE_UNAUTHORIZED_CA=true
      # https://docs.linkwarden.app/self-hosting/sso-oauth#authentik
      - NEXT_PUBLIC_AUTHENTIK_ENABLED=true
      - AUTHENTIK_ISSUER=${AUTHENTIK_ISSUER}
      - AUTHENTIK_CLIENT_ID=${AUTHENTIK_CLIENT_ID}
      - AUTHENTIK_CLIENT_SECRET=${AUTHENTIK_CLIENT_SECRET}
    labels:
      # Websecure
      traefik.http.routers.linkwarden.middlewares: chain-Domain-auth@file
      traefik.http.routers.linkwarden.tls.certresolver: ''
      # WebSecure local IP
      traefik.http.routers.linkwarden-privip.rule: Host(`${APP_DOMAIN}`) && ClientIP(`${PRIVATE_IPV4}`)
      traefik.http.routers.linkwarden-privip.middlewares: chain-Domain@file
      traefik.http.routers.linkwarden-privip.entrypoints: websecure
      traefik.http.routers.linkwarden-privip.service: linkwarden
      traefik.http.routers.linkwarden-privip.priority: 100
      traefik.http.routers.linkwarden-privip.tls.certresolver: ''
      # WUD-FH
      wud.tag.include: '^\d+\.\d+\.\d+$$'
      wud.watch: true
      wud.link.template: https://github.com/linkwarden/linkwarden/releases/tag/v$${major}.$${minor}.$${patch}

  linkwarden-db:
    pull_policy: missing
    image: postgres:16-alpine
    labels:
      # WUD-FH
      wud.tag.include: '^16-alpine$$'
      wud.watch.digest: true
      wud.watch: true
      wud.link.template: https://github.com/postgres/postgres/tag/REL_$${major}_$${minor}

  dbbackup:
    pull_policy: missing
    image: tiredofit/db-backup:4.1.9
    container_name: linkwarden-db-backup
    environment:
      - DEFAULT_COMPRESSION=GZ
      - DB01_TYPE=pgsql
      - DB01_HOST=linkwarden-db
      - DB01_NAME=linkwarden
      - DB01_USER=tipi
      - DB01_PASS=${LINKWARDEN_DB_PASSWORD}
      - CONTAINER_ENABLE_MONITORING=FALSE
      - DEFAULT_CLEANUP_TIME=1440
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA_DIR}/data/db-backup:/backup
    depends_on:
      - linkwarden-db
    networks:
      - tipi_main_network
    labels:
      # WUD-FH
      wud.tag.include: '^\d+\.\d+\.\d+$$'
      wud.watch: true
      wud.link.template: https://github.com/tiredofit/docker-db-backup/releases/tag/$${major}.$${minor}.$${patch}
