version: "3.7"

services:
  linkwarden:
    environment:
      # https://docs.linkwarden.app/self-hosting/environment-variables
      #- PAGINATION_TAKE_COUNT=
      #- STORAGE_FOLDER=
      #- AUTOSCROLL_TIMEOUT=
      #- NEXT_PUBLIC_CREDENTIALS_ENABLED=
      #- DISABLE_NEW_SSO_USERS=
      #- RE_ARCHIVE_LIMIT=
      #- NEXT_PUBLIC_MAX_FILE_SIZE=
      #- MAX_LINKS_PER_USER=
      #- ARCHIVE_TAKE_COUNT=
      #- BROWSER_TIMEOUT=
      # https://github.com/linkwarden/linkwarden/issues/381#issuecomment-1872982427
      - IGNORE_UNAUTHORIZED_CA=true
      # https://docs.linkwarden.app/self-hosting/sso-oauth#authentik
      - NEXT_PUBLIC_AUTHENTIK_ENABLED=true
      - AUTHENTIK_ISSUER=${AUTHENTIK_ISSUER}
      - AUTHENTIK_CLIENT_ID=${AUTHENTIK_CLIENT_ID}
      - AUTHENTIK_CLIENT_SECRET=${AUTHENTIK_CLIENT_SECRET}
    networks:
      - backend_network
    labels:
      # Websecure
      traefik.http.routers.linkwarden.middlewares: geoblock@file
      # Local domain secure
      traefik.http.routers.linkwarden-local.middlewares: local-ipallowlist@file

  linkwarden-db:
    networks: !override
      - backend_network

  dbbackup:
    image: tiredofit/db-backup:4.1.8
    container_name: linkwarden-db-backup
    environment:
      - DEFAULT_COMPRESSION=GZ
      - DB01_TYPE=pgsql
      - DB01_HOST=linkwarden-db
      - DB01_NAME=linkwarden
      - DB01_USER=tipi
      - DB01_PASS=${LINKWARDEN_DB_PASSWORD}
      - CONTAINER_ENABLE_MONITORING=FALSE
      - DEFAULT_CLEANUP_TIME=1440
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA_DIR}/data/db-backup:/backup
    depends_on:
      - linkwarden-db
    networks:
      - backend_network

networks:
  backend_network:
