services:
  wallos:
    pull_policy: missing
    labels:
      # Websecure
      traefik.http.routers.wallos-migrated.middlewares: chain-Domain-auth@file
      traefik.http.routers.wallos-migrated.tls.certresolver: ''
      # WebSecure local IP
      traefik.http.routers.wallos-migrated-privip.rule: Host(`${APP_DOMAIN}`) && ClientIP(`${PRIVATE_IPV4}`)
      traefik.http.routers.wallos-migrated-privip.middlewares: chain-Domain@file
      traefik.http.routers.wallos-migrated-privip.entrypoints: websecure
      traefik.http.routers.wallos-migrated-privip.service: wallos-migrated
      traefik.http.routers.wallos-migrated-privip.priority: 100
      traefik.http.routers.wallos-migrated-privip.tls.certresolver: ''
      # WUD-FH
      wud.tag.include: '^\d+\.\d+\.\d+$$'
      wud.watch: true
      wud.link.template: https://github.com/ellite/Wallos/releases/tag/v$${major}.$${minor}.$${patch}
