version: "3.7"

services:
  moodist:
    labels:
      # Websecure
      traefik.http.routers.moodist.middlewares: authentik@file, geoblock@file
      # Local domain secure
      traefik.http.routers.moodist-local.middlewares: local-ipallowlist@file
