services:
  ddns-updater:
    dns:
      - 1.1.1.1
      - 1.0.0.1
    environment:
      - TZ=${TZ}
      - SHOUTRRR_ADDRESSES=pushover://shoutrrr:${PUSHOVER_APITOKEN}@${PUSHOVER_USERKEY}/?devices=${PUSHOVER_DEVICES}
    volumes:
      - ${APP_DATA_DIR}/data:/updater/data
    labels:
      # Websecure
      traefik.http.routers.ddns-updater.middlewares: chain-Domain-auth@file
      traefik.http.routers.ddns-updater.tls.certresolver: ''
