services:
  ddns-updater:
    dns:
      - 1.1.1.1
      - 1.0.0.1
    environment:
      - TZ=${TZ}
      - SHOUTRRR_ADDRESSES=pushover://shoutrrr:${PUSHOVER_APITOKEN}@${PUSHOVER_USERKEY}/?devices=${PUSHOVER_DEVICES}
    volumes:
      - ${APP_DATA_DIR}/data:/updater/data
    ports: !reset []
    labels:
      # Websecure
      traefik.http.routers.ddns-updater.tls.certresolver: ''
      # Local domain secure
      traefik.http.routers.ddns-updater-local.middlewares: chain-localDomain-auth@file
