services:
  jellyfin:
    volumes:
      - ${APP_USER_DATA_DIR}/music/:/media/music
      - ${APP_USER_DATA_DIR}/video/:/media/video
    labels:
      # Websecure
      traefik.http.routers.jellyfin.middlewares: chain-Domain-auth@file
      traefik.http.routers.jellyfin.tls.certresolver: ''
      # WebSecure local IP
      traefik.http.routers.jellyfin-privip.rule: Host(`${APP_DOMAIN}`) && ClientIP(`${PRIVATE_IPV4}`)
      traefik.http.routers.jellyfin-privip.middlewares: chain-Domain@file
      traefik.http.routers.jellyfin-privip.entrypoints: websecure
      traefik.http.routers.jellyfin-privip.service: jellyfin
      traefik.http.routers.jellyfin-privip.priority: 100
      traefik.http.routers.jellyfin-privip.tls.certresolver: ''
