version: "3.7"
services:
  jellyfin:
    volumes:
      - ${APP_USER_DATA_DIR}/music/:/media/music
      - ${APP_USER_DATA_DIR}/video/:/media/video
    labels:
      # Websecure
      traefik.http.routers.jellyfin.middlewares: plugin-geoblock@file, forwardAuth-authentik@file
      traefik.http.routers.jellyfin.tls.certresolver: ''
      # Local domain secure
      traefik.http.routers.jellyfin-local.middlewares: ipAllowList-local@file
