services:
  moodist:
    pull_policy: missing
    labels:
      # Websecure
      traefik.http.routers.moodist-migrated.middlewares: chain-Domain-auth@file
      traefik.http.routers.moodist-migrated.tls.certresolver: ''
      # WebSecure local IP
      traefik.http.routers.moodist-migrated-privip.rule: Host(`${APP_DOMAIN}`) && ClientIP(`${PRIVATE_IPV4}`)
      traefik.http.routers.moodist-migrated-privip.middlewares: chain-Domain@file
      traefik.http.routers.moodist-migrated-privip.entrypoints: websecure
      traefik.http.routers.moodist-migrated-privip.service: moodist-migrated
      traefik.http.routers.moodist-migrated-privip.priority: 100
      traefik.http.routers.moodist-migrated-privip.tls.certresolver: ''
      # WUD-FH
      wud.tag.include: '^\d+\.\d+\.\d+$$'
      wud.watch: true
      wud.link.template: https://github.com/remvze/moodist/blob/main/CHANGELOG.md
