services:
  dozzle:
    labels:
      # Websecure
      traefik.http.routers.dozzle.middlewares: geoblock@file
      # Local domain secure
      traefik.http.routers.dozzle-local.middlewares: local-ipallowlist@file
