services:
  dozzle:
    labels:
      # Websecure
      traefik.http.routers.dozzle.middlewares: chain-Domain-auth@file
      traefik.http.routers.dozzle.tls.certresolver: ''
      # WUD
      wud.tag.include: '^v\d+\.\d+\.\d+$$'
