services:
  wekan:
    pull_policy: missing
    environment:
      - OAUTH2_ENABLED=true
      - OAUTH2_LOGIN_STYLE=redirect
      - OAUTH2_CLIENT_ID=${OAUTH2_CLIENT_ID}
      - OAUTH2_SERVER_URL=${OAUTH2_SERVER_URL}
      - OAUTH2_AUTH_ENDPOINT=/application/o/authorize/
      - OAUTH2_USERINFO_ENDPOINT=/application/o/userinfo/
      - OAUTH2_TOKEN_ENDPOINT=/application/o/token/
      - OAUTH2_SECRET=${OAUTH2_SECRET}
      - OAUTH2_FULLNAME_MAP=given_name
      - OAUTH2_EMAIL_MAP=email
      - OAUTH2_ID_MAP=sub
      - OAUTH2_USERNAME_MAP=email
      - CORS=*
      - CORS_ALLOW_HEADERS=Authorization,Content-Type
    labels:
      # Websecure
      traefik.http.routers.wekan.middlewares: chain-Domain-auth@file
      traefik.http.routers.wekan.tls.certresolver: ''
      # WUD-FH
      wud.tag.include: '^v\d+\.\d+$$'
      wud.watch: true
      wud.link.template: https://github.com/wekan/wekan/releases/tag/v$${major}.$${minor}

  wekan-db:
    pull_policy: missing
    labels:
      # WUD-FH
      wud.tag.include: '^\d+$$'
      wud.watch: false
      wud.watch.digest: true

  dbbackup:
    image: tiredofit/db-backup:4.1.9
    pull_policy: missing
    container_name: wekan-db-backup
    environment:
      - DEFAULT_COMPRESSION=GZ
      - DB01_TYPE=mongo
      - DB01_HOST=wekan-db
      - DB01_NAME=wekan
      - CONTAINER_ENABLE_MONITORING=FALSE
      - DEFAULT_CLEANUP_TIME=1440
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA_DIR}/data/db-backup:/backup
    depends_on:
      - wekan-db
    networks:
      - tipi_main_network
    labels:
      # WUD-FH-FH
      wud.tag.include: '^\d+\.\d+\.\d+$$'
      wud.watch: true
      wud.link.template: https://github.com/tiredofit/docker-db-backup/releases/tag/$${major}.$${minor}.$${patch}
