services:
  freshrss:
    image: freshrss/freshrss:1.25.0
    environment:
      - TZ=${TIMEZONE}
      - CRON_MIN=5,20,35,50
      # OIDC
      - TRUSTED_PROXY=172.16.0.1/12
      - OIDC_ENABLED=1
      - OIDC_PROVIDER_METADATA_URL=${OIDC_PROVIDER_METADATA_URL}
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
      - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
      - OIDC_REMOTE_USER_CLAIM=preferred_username
      - OIDC_SCOPES=openid email profile
      - OIDC_X_FORWARDED_HEADERS=X-Forwarded-Port X-Forwarded-Proto X-Forwarded-Host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA_DIR}/data/config:/config
      - ${APP_DATA_DIR}/data/data:/var/www/FreshRSS/data
      - ${APP_DATA_DIR}/data/extensions:/var/www/FreshRSS/extensions
    labels:
      # https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/freshrss/docker-compose-proxy.yml
      # Main
      traefik.http.middlewares.freshrss.compress: true
      # Websecure
      traefik.http.routers.freshrss.middlewares: freshrss,chain-Domain-auth@file
      traefik.http.routers.freshrss.tls.certresolver: ''
      # WUD
      wud.tag.include: '^\d+\.\d+\.\d+$$'
