services:
  hello-world:
    labels:
      # Websecure
      traefik.http.routers.hello-world-migated.middlewares: chain-Domain-auth@file
      traefik.http.routers.hello-world-migated.tls.certresolver: ''
      # WebSecure local IP
      traefik.http.routers.hello-world-migated-privip.rule: Host(`${APP_DOMAIN}`) && ClientIP(`${PRIVATE_IPV4}`)
      traefik.http.routers.hello-world-migated-privip.middlewares: chain-Domain@file
      traefik.http.routers.hello-world-migated-privip.entrypoints: websecure
      traefik.http.routers.hello-world-migated-privip.service: hello-world-migrated
      traefik.http.routers.hello-world-migated-privip.priority: 100
      traefik.http.routers.hello-world-migated-privip.tls.certresolver: ''
