services:
  uptime-kuma:
    ports: !reset []
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      # Websecure
      traefik.http.routers.uptime-kuma.middlewares: chain-Domain-auth@file
      traefik.http.routers.uptime-kuma.tls.certresolver: ''
      # Local domain secure
      traefik.http.routers.uptime-kuma-local.middlewares: chain-localDomain-deny@file
