version: "3.7"
services:
  uptime-kuma:
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      # Websecure
      traefik.http.routers.uptime-kuma.middlewares: authentik@file, geoblock@file
      # Local domain secure
      traefik.http.routers.uptime-kuma-local.middlewares: local-ipallowlist@file
