version: "3.7"
services:
  uptime-kuma:
    ports: !reset []
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      # Websecure
      traefik.http.routers.uptime-kuma.middlewares: plugin-geoblock@file, forwardAuth-authentik@file
      traefik.http.routers.uptime-kuma.tls.certresolver: ''
      # Local domain secure
      traefik.http.routers.uptime-kuma-local.middlewares: ipAllowList-none@file
