services:
  uptime-kuma:
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      # Websecure
      traefik.http.routers.uptime-kuma.middlewares: chain-Domain-auth@file
      traefik.http.routers.uptime-kuma.tls.certresolver: ''
      # WUD
      wud.tag.include: '^\d+$$'
