services:
  bookstack:
    pull_policy: missing
    labels:
      # Websecure
      traefik.http.routers.bookstack-migrated.middlewares: chain-Domain-auth@file
      traefik.http.routers.bookstack-migrated.tls.certresolver: ''
      # WUD-FH
      wud.tag.include: '^\d+\.\d+\.\d+$$'
      wud.watch: true

  bookstack-db:
    pull_policy: missing
    image: lscr.io/linuxserver/mariadb
    networks:
      shared_docker-db-backup_network:
        gw_priority: 0
    labels:
      # WUD-FH
      wud.tag.include: '^$$'
      wud.watch: false
      wud.watch.digest: true

networks:
  shared_docker-db-backup_network:
    external: true
