version: "3.7"

services:
  metube:
    image: ghcr.io/alexta69/metube:2024-12-08
    ports: !reset []
    volumes:
      - ${APP_USER_DATA_DIR}/video/youtube/:/downloads
    environment:
      - DOWNLOAD_DIRS_INDEXABLE=true
      - DELETE_FILE_ON_TRASHCAN=true
    labels:
      # Websecure
      traefik.http.routers.metube.middlewares: plugin-geoblock@file, forwardAuth-authentik@file
      traefik.http.routers.metube.tls.certresolver: ''
