version: "3.7"

services:
  metube:
    volumes:
      - ${APP_USER_DATA_DIR}/video/youtube/:/downloads
    environment:
      - DOWNLOAD_DIRS_INDEXABLE=true
    labels:
      # Local domain secure
      traefik.http.routers.metube-local.middlewares: local-ipallowlist@file
