services:
  immich:
    # Ensure the image is not pulled if present
    pull_policy: missing
    labels:
      # Websecure
      # Use the chain-Domain-auth middleware for domain handling
      traefik.http.routers.immich-falkheiland.middlewares: chain-Domain-auth@file
      # Use the default certresolver
      traefik.http.routers.immich-falkheiland.tls.certresolver: ''

  immich-machine-learning:
    # Ensure the image is not pulled if present
    pull_policy: missing

  immich-redis:
    # Ensure the image is not pulled if present
    pull_policy: missing

  immich-db:
    # Ensure the image is not pulled if present
    pull_policy: missing
    networks:
      # This network is shared with the docker-db-backup app
      shared_docker-db-backup_network:
        gw_priority: 0

networks:
  # This network is shared with the docker-db-backup app
  shared_docker-db-backup_network:
    external: true
