version: "2.1"

services:
  nocodb:
    labels:
      # Websecure
      traefik.http.routers.nocodb.middlewares: authentik@file, geoblock@file
      # Local domain secure
      traefik.http.routers.nocodb-local.middlewares: local-ipallowlist@file

  nocodb-db:
    #image: postgres:16-alpine
    image: postgres:16
    networks:
      - backend_network

  dbbackup:
    image: tiredofit/db-backup:4.0.34
    container_name: nocodb-db-backup
    environment:
      - DEFAULT_COMPRESSION=GZ
      - DB01_TYPE=pgsql
      - DB01_HOST=nocodb-db
      - DB01_NAME=nocodb
      - DB01_USER=postgres
      - DB01_PASS=${NOCODB_DB_PASSWORD}
      - CONTAINER_ENABLE_MONITORING=FALSE
      - DEFAULT_CLEANUP_TIME=1440
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA_DIR}/data/db-backup:/backup
    depends_on:
      - nocodb-db
    networks:
      - backend_network

networks:
  backend_network:
