version: '3.9'
services:
  searxng:
    labels:
      # Websecure
      traefik.http.routers.searxng.tls.certresolver: ''
      # Local domain secure
      traefik.http.routers.searxng-local.middlewares: ipAllowList-local@file
