services:
  searxng:
    labels:
      # Websecure
      traefik.http.routers.searxng.middlewares: chain-Domain-auth@file
      traefik.http.routers.searxng.tls.certresolver: ''
      # WebSecure local IP
      traefik.http.routers.searxng-privip.rule: Host(`${APP_DOMAIN}`) && ClientIP(`${PRIVATE_IPV4}`)
      traefik.http.routers.searxng-privip.middlewares: chain-Domain@file
      traefik.http.routers.searxng-privip.entrypoints: websecure
      traefik.http.routers.searxng-privip.service: searxng
      traefik.http.routers.searxng-privip.priority: 100
      traefik.http.routers.searxng-privip.tls.certresolver: ''
      # WUD
      wud.tag.include: '^\d+\.\d+\.\d+-\d+-.*$$'
      wud.tag.transform: '^(\d+\.\d+\.\d+-\d+)-.*$$ => $$1'
