version: "3.8"

services:
  crowdsec:
    ports: !reset []
    environment:
      - COLLECTIONS= crowdsecurity/linux crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/whitelist-good-actors crowdsecurity/sshd firix/authentik

  crowdsec-dashboard:
    labels:
      # Local domain secure
      traefik.http.routers.crowdsec-local.middlewares: ipAllowList-local@file
