services:
  nextcloud:
    # Ensure the image is not pulled if present
    pull_policy: missing

  nextcloud-web:
    # Ensure the image is not pulled if present
    pull_policy: missing
    labels:
      # Websecure
      # Use the chain-Domain middleware for domain handling
      traefik.http.routers.nextcloud-fpm-falkheiland.middlewares: chain-Domain@file
      # Use the default certresolver
      traefik.http.routers.nextcloud-fpm-falkheiland.tls.certresolver: ''

  nextcloud-cron:
    # Ensure the image is not pulled if present
    pull_policy: missing

  nextcloud-redis:
    # Ensure the image is not pulled if present
    pull_policy: missing

  nextcloud-db:
    # Ensure the image is not pulled if present
    pull_policy: missing
    networks:
      # This network is shared with the docker-db-backup app
      shared_docker-db-backup_network:
        gw_priority: 0

networks:
  nextcloud-fpm_falkheiland_network:
    external: false
    # Reset to default IPAM configuration
    ipam: !reset []
  # This network is shared with the docker-db-backup app
  shared_docker-db-backup_network:
    external: true
